version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - web-project
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - web-project
networks:
  web-project: